<?php

/**
 * This is the model base class for the table "{{queries}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Queries".
 *
 * Columns in table "{{queries}}" available as properties of the model,
 * followed by relations of table "{{queries}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $member_id
 * @property string $created_at
 * @property string $provider
 * @property string $data
 * @property string $query
 * @property string $lang
 *
 * @property Members $member
 */
abstract class BaseQueries extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{queries}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Queries|Queries', $n);
	}

	public static function representingColumn() {
		return 'provider';
	}

	public function rules() {
		return array(
			array('member_id, provider, data, query, lang', 'required'),
			array('member_id', 'numerical', 'integerOnly'=>true),
			array('provider, lang', 'length', 'max'=>128),
			array('data', 'length', 'max'=>256),
			array('created_at', 'safe'),
			array('created_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, member_id, created_at, provider, data, query, lang', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'member' => array(self::BELONGS_TO, 'Members', 'member_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'member_id' => null,
			'created_at' => Yii::t('app', 'Create At'),
			'provider' => Yii::t('app', 'Provider'),
			'data' => Yii::t('app', 'Data'),
			'query' => Yii::t('app', 'Query'),
			'lang' => Yii::t('app', 'Lang'),
			'member' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('member_id', $this->member_id);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('provider', $this->provider, true);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('query', $this->query, true);
		$criteria->compare('lang', $this->lang, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}