<?php

/**
 * This is the model base class for the table "{{languages_support}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LanguagesSupport".
 *
 * Columns in table "{{languages_support}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $lang
 * @property boolean $support
 * @property string $alias
 *
 */
abstract class BaseLanguagesSupport extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{languages_support}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LanguagesSupport|LanguagesSupports', $n);
	}

	public static function representingColumn() {
		return 'lang';
	}

	public function rules() {
		return array(
			array('lang, alias', 'required'),
			array('lang, alias', 'length', 'max'=>128),
			array('support', 'safe'),
			array('support', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, lang, support, alias', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'lang' => Yii::t('app', 'Lang'),
			'support' => Yii::t('app', 'Support'),
			'alias' => Yii::t('app', 'Alias'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('lang', $this->lang, true);
		$criteria->compare('support', $this->support);
		$criteria->compare('alias', $this->alias, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

}