<?php

/**
 * This is the model base class for the table "{{queries}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Queries".
 *
 * Columns in table "{{queries}}" available as properties of the model,
 * followed by relations of table "{{queries}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $create_at
 * @property string $provider
 * @property string $data
 * @property string $query
 * @property string $lang
 *
 * @property Users $user
 */
abstract class BaseQueries extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{queries}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Queries|Queries', $n);
	}

	public static function representingColumn() {
		return 'provider';
	}

	public function rules() {
		return array(
			array('user_id, provider, data, query, lang', 'required'),
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('provider, lang', 'length', 'max'=>128),
			array('data', 'length', 'max'=>256),
			array('create_at', 'safe'),
			array('create_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, create_at, provider, data, query, lang', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'create_at' => Yii::t('app', 'Create At'),
			'provider' => Yii::t('app', 'Provider'),
			'data' => Yii::t('app', 'Data'),
			'query' => Yii::t('app', 'Query'),
			'lang' => Yii::t('app', 'Lang'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('create_at', $this->create_at, true);
		$criteria->compare('provider', $this->provider, true);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('query', $this->query, true);
		$criteria->compare('lang', $this->lang, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}