<?php

/**
 * This is the model base class for the table "{{loans}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Loans".
 *
 * Columns in table "{{loans}}" available as properties of the model,
 * followed by relations of table "{{loans}}" available as properties of the model.
 *
 * @property string $id
 * @property string $leader
 * @property string $currency
 * @property string $title_en_us
 * @property string $title_es
 * @property integer $id_loans_activity
 * @property string $image
 * @property integer $id_loans_countries
 * @property string $partner
 * @property string $amount
 * @property integer $term
 * @property string $contribution
 * @property string $loan_date
 * @property string $loan_update
 * @property integer $id_loans_status
 * @property string $paidback
 * @property string $loss_currency
 * @property string $loss_defaut
 * @property string $created_at
 * @property string $updated_at
 *
 * @property LoansActivities $idLoansActivity
 * @property LoansCountries $idLoansCountries
 * @property LoansStatus $idLoansStatus
 */
abstract class BaseLoans extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{loans}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Loans|Loans', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('id, id_loans_activity, id_loans_countries, id_loans_status', 'required'),
			array('id_loans_activity, id_loans_countries, term, id_loans_status', 'numerical', 'integerOnly'=>true),
			array('id, leader, currency, title_en_us, title_es, image, partner', 'length', 'max'=>255),
			array('amount, contribution, loan_date, loan_update, paidback, loss_currency, loss_defaut, created_at, updated_at', 'safe'),
			array('leader, currency, title_en_us, title_es, image, partner, amount, term, contribution, loan_date, loan_update, paidback, loss_currency, loss_defaut, created_at, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, leader, currency, title_en_us, title_es, id_loans_activity, image, id_loans_countries, partner, amount, term, contribution, loan_date, loan_update, id_loans_status, paidback, loss_currency, loss_defaut, created_at, updated_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idLoansActivity' => array(self::BELONGS_TO, 'LoansActivities', 'id_loans_activity'),
			'idLoansCountries' => array(self::BELONGS_TO, 'LoansCountries', 'id_loans_countries'),
			'idLoansStatus' => array(self::BELONGS_TO, 'LoansStatus', 'id_loans_status'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'leader' => Yii::t('app', 'Leader'),
			'currency' => Yii::t('app', 'Currency'),
			'title_en_us' => Yii::t('app', 'Title En Us'),
			'title_es' => Yii::t('app', 'Title Es'),
			'id_loans_activity' => null,
			'image' => Yii::t('app', 'Image'),
			'id_loans_countries' => null,
			'partner' => Yii::t('app', 'Partner'),
			'amount' => Yii::t('app', 'Amount'),
			'term' => Yii::t('app', 'Term'),
			'contribution' => Yii::t('app', 'Contribution'),
			'loan_date' => Yii::t('app', 'Loan Date'),
			'loan_update' => Yii::t('app', 'Loan Update'),
			'id_loans_status' => null,
			'paidback' => Yii::t('app', 'Paidback'),
			'loss_currency' => Yii::t('app', 'Loss Currency'),
			'loss_defaut' => Yii::t('app', 'Loss Defaut'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'idLoansActivity' => null,
			'idLoansCountries' => null,
			'idLoansStatus' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('leader', $this->leader, true);
		$criteria->compare('currency', $this->currency, true);
		$criteria->compare('title_en_us', $this->title_en_us, true);
		$criteria->compare('title_es', $this->title_es, true);
		$criteria->compare('id_loans_activity', $this->id_loans_activity);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('id_loans_countries', $this->id_loans_countries);
		$criteria->compare('partner', $this->partner, true);
		$criteria->compare('amount', $this->amount, true);
		$criteria->compare('term', $this->term);
		$criteria->compare('contribution', $this->contribution, true);
		$criteria->compare('loan_date', $this->loan_date, true);
		$criteria->compare('loan_update', $this->loan_update, true);
		$criteria->compare('id_loans_status', $this->id_loans_status);
		$criteria->compare('paidback', $this->paidback, true);
		$criteria->compare('loss_currency', $this->loss_currency, true);
		$criteria->compare('loss_defaut', $this->loss_defaut, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}