<?php

/**
 * This is the model base class for the table "{{adtracks}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Adtracks".
 *
 * Columns in table "{{adtracks}}" available as properties of the model,
 * followed by relations of table "{{adtracks}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $user_id
 * @property integer $member_id
 * @property integer $adtracks_sources_id
 * @property string $domain
 * @property string $url
 * @property string $created_at
 * @property string $usertime
 *
 * @property Members $member
 * @property AdtracksSources $adtracksSources
 */
abstract class BaseAdtracks extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{adtracks}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Adtracks|Adtracks', $n);
	}

	public static function representingColumn() {
		return 'domain';
	}

	public function rules() {
		return array(
			array('adtracks_sources_id, created_at', 'required'),
			array('member_id, adtracks_sources_id', 'numerical', 'integerOnly'=>true),
			array('user_id, domain', 'length', 'max'=>255),
			array('url, usertime', 'safe'),
			array('user_id, member_id, domain, url, usertime', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, member_id, adtracks_sources_id, domain, url, created_at, usertime', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'member' => array(self::BELONGS_TO, 'Members', 'member_id'),
			'adtracksSources' => array(self::BELONGS_TO, 'AdtracksSources', 'adtracks_sources_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'member_id' => null,
			'adtracks_sources_id' => null,
			'domain' => Yii::t('app', 'Domain'),
			'url' => Yii::t('app', 'Url'),
			'created_at' => Yii::t('app', 'Created At'),
			'usertime' => Yii::t('app', 'Usertime'),
			'member' => null,
			'adtracksSources' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id, true);
		$criteria->compare('member_id', $this->member_id);
		$criteria->compare('adtracks_sources_id', $this->adtracks_sources_id);
		$criteria->compare('domain', $this->domain, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('usertime', $this->usertime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}