<?php

/**
 * This is the model base class for the table "{{achievements_types}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AchievementsTypes".
 *
 * Columns in table "{{achievements_types}}" available as properties of the model,
 * followed by relations of table "{{achievements_types}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name_en
 * @property string $name_es
 * @property string $icon
 *
 * @property Achievements[] $achievements
 */
abstract class BaseAchievementsTypes extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{achievements_types}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AchievementsTypes|AchievementsTypes', $n);
	}

	public static function representingColumn() {
		return 'name_en';
	}

	public function rules() {
		return array(
			array('name_en, name_es, icon', 'length', 'max'=>255),
			array('name_en, name_es, icon', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name_en, name_es, icon', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'achievements' => array(self::HAS_MANY, 'Achievements', 'achievement_type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name_en' => Yii::t('app', 'Name En'),
			'name_es' => Yii::t('app', 'Name Es'),
			'icon' => Yii::t('app', 'Icon'),
			'achievements' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name_en', $this->name_en, true);
		$criteria->compare('name_es', $this->name_es, true);
		$criteria->compare('icon', $this->icon, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}