<?php

/**
 * This is the model base class for the table "{{threats}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Threats".
 *
 * Columns in table "{{threats}}" available as properties of the model,
 * followed by relations of table "{{threats}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $service_id
 * @property string $domain
 * @property string $url
 * @property string $create_at
 *
 * @property Users $user
 * @property Services $service
 */
abstract class BaseThreats extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{threats}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Threats|Threats', $n);
	}

	public static function representingColumn() {
		return 'domain';
	}

	public function rules() {
		return array(
			array('user_id, service_id, create_at', 'required'),
			array('user_id, service_id', 'numerical', 'integerOnly'=>true),
			array('domain', 'length', 'max'=>255),
			array('url', 'safe'),
			array('domain, url', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, service_id, domain, url, create_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
			'service' => array(self::BELONGS_TO, 'Services', 'service_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'service_id' => null,
			'domain' => Yii::t('app', 'Domain'),
			'url' => Yii::t('app', 'Url'),
			'create_at' => Yii::t('app', 'Create At'),
			'user' => null,
			'service' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('service_id', $this->service_id);
		$criteria->compare('domain', $this->domain, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('create_at', $this->create_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}