<?php

/**
 * This is the model base class for the table "{{loans_status}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LoansStatus".
 *
 * Columns in table "{{loans_status}}" available as properties of the model,
 * followed by relations of table "{{loans_status}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name_en_us
 * @property string $name_es
 *
 * @property Loans[] $loans
 */
abstract class BaseLoansStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{loans_status}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Loan Status|Loan Status', $n);
	}

	public static function representingColumn() {
		return 'name_en_us';
	}

	public function rules() {
		return array(
			array('name_en_us, name_es', 'length', 'max'=>255),
			array('name_en_us, name_es', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name_en_us, name_es', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'loans' => array(self::HAS_MANY, 'Loans', 'id_loans_status'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name_en_us' => Yii::t('app', 'Name En Us'),
			'name_es' => Yii::t('app', 'Name Es'),
			'loans' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name_en_us', $this->name_en_us, true);
		$criteria->compare('name_es', $this->name_es, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}