<?php

/**
 * This is the model base class for the table "{{services}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Services".
 *
 * Columns in table "{{services}}" available as properties of the model,
 * followed by relations of table "{{services}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $category_id
 * @property string $name
 * @property string $url
 *
 * @property Categories $category
 * @property Threats[] $threats
 */
abstract class BaseServices extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{services}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Services|Services', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('category_id', 'required'),
			array('category_id', 'numerical', 'integerOnly'=>true),
			array('name, url', 'length', 'max'=>255),
			array('name, url', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, category_id, name, url', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'category' => array(self::BELONGS_TO, 'Categories', 'category_id'),
			'threats' => array(self::HAS_MANY, 'Threats', 'services_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'category_id' => null,
			'name' => Yii::t('app', 'Name'),
			'url' => Yii::t('app', 'Url'),
			'category' => null,
			'threats' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('url', $this->url, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}