<?php

/**
 * This is the model base class for the table "{{adtracks_types}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AdtracksTypes".
 *
 * Columns in table "{{adtracks_types}}" available as properties of the model,
 * followed by relations of table "{{adtracks_types}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 *
 * @property AdtracksSources[] $adtracksSources
 */
abstract class BaseAdtracksTypes extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{adtracks_types}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Webtrack Types|Webtrack Types', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'length', 'max'=>255),
			array('name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'adtracksSources' => array(self::HAS_MANY, 'AdtracksSources', 'adtrack_type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'adtracksSources' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('LOWER(name)', strtolower($this->name), true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}