<?php

/**
 * This is the model base class for the table "{{queries_blacklist}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "QueriesBlacklist".
 *
 * Columns in table "{{queries_blacklist}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $category
 * @property string $word
 * @property string $lang
 * @property string $create_at
 *
 */
abstract class BaseQueriesBlacklist extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{queries_blacklist}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'QueriesBlacklist|QueriesBlacklists', $n);
	}

	public static function representingColumn() {
		return 'category';
	}

	public function rules() {
		return array(
			array('lang', 'required'),
			array('category, word', 'length', 'max'=>255),
			array('lang', 'length', 'max'=>128),
			array('create_at', 'safe'),
			array('category, word, create_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, category, word, lang, create_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'category' => Yii::t('app', 'Category'),
			'word' => Yii::t('app', 'Word'),
			'lang' => Yii::t('app', 'Lang'),
			'create_at' => Yii::t('app', 'Create At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('category', $this->category, true);
		$criteria->compare('word', $this->word, true);
		$criteria->compare('lang', $this->lang, true);
		$criteria->compare('create_at', $this->create_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}