<?php

/**
 * This is the model base class for the table "{{history}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "History".
 *
 * Columns in table "{{history}}" available as properties of the model,
 * followed by relations of table "{{history}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $domain
 * @property string $url
 * @property string $created_at
 *
 * @property Users $user
 */
abstract class BaseHistory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{history}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'History|Histories', $n);
	}

	public static function representingColumn() {
		return 'domain';
	}

	public function rules() {
		return array(
			array('user_id', 'required'),
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('domain', 'length', 'max'=>255),
			array('url, created_at', 'safe'),
			array('domain, url, created_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, domain, url, created_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'domain' => Yii::t('app', 'Domain'),
			'url' => Yii::t('app', 'Url'),
			'created_at' => Yii::t('app', 'Create At'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('domain', $this->domain, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('created_at', $this->created_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}