<?php

/**
 * This is the model base class for the table "{{adtracks_sources}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AdtracksSources".
 *
 * Columns in table "{{adtracks_sources}}" available as properties of the model,
 * followed by relations of table "{{adtracks_sources}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $adtrack_type_id
 * @property string $name
 * @property string $url
 * @property string $created_at
 * @property string $updated_at
 *
 * @property Adtracks[] $adtracks
 * @property AdtracksTypes $adtrackType
 * @property Whitelists[] $whitelists
 */
abstract class BaseAdtracksSources extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{adtracks_sources}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Webtrack Sources|Webtrack Sources', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('adtrack_type_id', 'required'),
			array('adtrack_type_id', 'numerical', 'integerOnly'=>true),
			array('name, url', 'length', 'max'=>255),
			array('created_at, updated_at', 'safe'),
			array('name, url, created_at, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, adtrack_type_id, name, url, created_at, updated_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'adtracks' => array(self::HAS_MANY, 'Adtracks', 'adtracks_sources_id'),
			'adtrackType' => array(self::BELONGS_TO, 'AdtracksTypes', 'adtrack_type_id'),
			'whitelists' => array(self::HAS_MANY, 'Whitelists', 'adtracks_sources_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'adtrack_type_id' => null,
			'name' => Yii::t('app', 'Name'),
			'url' => Yii::t('app', 'Url'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'adtracks' => null,
			'adtrackType' => null,
			'whitelists' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('adtrack_type_id', $this->adtrack_type_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}