<?php

/**
 * This is the model base class for the table "{{profiles}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Profiles".
 *
 * Columns in table "{{profiles}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $user_id
 * @property string $lastname
 * @property string $firstname
 *
 */
abstract class BaseProfiles extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{profiles}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Profiles|Profiles', $n);
	}

	public static function representingColumn() {
		return 'lastname';
	}

	public function rules() {
		return array(
			array('lastname, firstname', 'length', 'max'=>50),
			array('lastname, firstname', 'default', 'setOnEmpty' => true, 'value' => null),
			array('user_id, lastname, firstname', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => Yii::t('app', 'User'),
			'lastname' => Yii::t('app', 'Lastname'),
			'firstname' => Yii::t('app', 'Firstname'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('LOWER(lastname)', strtolower($this->lastname), true);
		$criteria->compare('LOWER(firstname)', strtolower($this->firstname), true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}