 <!-- main content -->
     
<div id="tgd-page-title">
  <div class="container">
    <div class="row">
      <h2>Frequently Asked Questions</h2>
    </div>
  </div>
</div> 

<div class="wrapper"> 
  <section id="tgd-page-content">
    <div class="container">
      <div class="row clearfix">
        <div class="col-xs-6 faq-index" style="padding-right: 0;"> <!-- required for floating -->
          <!-- Nav tabs -->
          <ul class="nav nav-tabs tabs-left"><!-- 'tabs-right' for right tabs -->
            <li class="active"><a href="#company" data-toggle="tab">Company</a></li>
            <li><a href="#service" data-toggle="tab">Service</a></li>
            <li><a href="#membership" data-toggle="tab">Membership</a></li>
            <li><a href="#collaborators" data-toggle="tab">Collaborators</a></li>
          </ul>
        </div>

        <div class="col-xs-10 faq">
          <!-- Tab panes -->
          <div class="tab-content">
            <div class="tab-pane active" id="company">
              <ul class="clearfix">
                <li>
                  <em>What is TheGoodData Mission?</em>
                  <p>We help people to enjoy the ownership of their data.</p>
                </li>
                <li>
                  <em>Why did you start the company?</em>
                  <p>We believe that data will be the main source of wealth in the new economy in the same way that land or labour had been in the past. Most of this data is being “produced” by individuals; however they do not act as owners, since most of that data is processed and traded by corporations without Customers’ knowledge or lacking a fair agreement.</p>
                  <p>We want to help people to be aware of the data they produce, to control who has access to it and to ensure that, when people decide to share their data, they receive the maximum benefit out of doing so. In this way Customers will not only be wealthier, will also improve their relationships with corporations who will not longer treat them as a product or as captive consumers.</p>
                </li>
                <li>
                  <em>What are your starting business goals?</em>
                  <p>Our first objective is to help people to effectively own their browsing data. This means helping them control who has access to their data and maximizing the social benefit of said data if users decide to anonymously trade part of it.</p>
                </li>
                <li>
                  <em>How do you make money?</em>
                  <p>TheGoodData aims to be self-financed by the revenues generated by the data you allow us to trade, in addition to donations from our supporters. Access to our services is free, irrespective of whether you decide to trade part of your data. We believe that you have to make this decision freely.</p>
                </li>
                <li>
                  <em>How do I know you are not sharing any sensitive or personally identifiable information?</em>
                  <p>In short, the GitHub logos and Octocat represent only GitHub and should not be used to represent your products. You may also read the official legal terms, if you’re into that.</p>
                </li>
                <li>
                  <em>Why are you organized as a cooperative?</em>
                  <p>Our company mission is extremely ambitious. It will only be achievable with the active collaboration of large amounts of people. We believe that this involvement can  be enabled through a platform that facilitates transparency, participation and fairness. </p>
                  <p>For this reason, TheGoodData has taken the legal form of an Industrial and Provident Society in the UK. It is a for-profit cooperative, in which users of the service become company owners if they apply for it (Members is the legal term). In that way important decisions including the use of benefits and the property of key assets such as  the data gathered, remain in the hands of our Members.</p>
                </li>
                <li>
                  <em>Does TheGoodData have any financial investors?</em>
                  <p>The only owners of TheGoodData at this point are its Members. In the future, only upon the approval of Members, some financial investors might be  brought in to boost growth and ensure the successful accomplishment of our mission. These investors would have some rightsq limitations in order to ensure that Members remain in control of the company.</p>
                </li>
              </ul>
            </div>
            <div class="tab-pane" id="service">
              <ul class="clearfix">
                <li>
                  <em>What is TheGoodData service</em>
                  <p>TheGoodData service as it exists today is an extension that helps you to control the browsing data that you produce, and use it for a good cause, should you wish to. It stops major third parties from tracking the webpages you viit and only if you agree to do so, trades non sensitive anonymised search data with brokers, reinvesting 100% of the money earned in Social Good projects and in improving TheGoodData service.</p>
                </li>
                <li>
                  <em>Which browsers does TheGoodData support?</em>
                  <p>TheGoodData is only available for Chrome at this point. We encourge you to help us develop the open source extension for other browsers enjoying the benefits of our Coder’s Program.</p>
                </li>
                <li>
                  <em>How do I use TheGoodData service?</em>
                  <p>TheGoodData runs automatically in the background, so you do not have to do anything after installing the extension. You can click TheGoodData icon in your toolbar to view, block, or unblock third-party requests or to otherwise change the default settings. You can also view more detailed information about threats that have been blocked, as well as company achievements  by visiting our website.</p>
                </li>
                <li>
                  <em>How does TheGoodData work?</em>
                  <p>TheGoodData uses opensource Disconnect.me technology to block data requests from over 2000 third party tracking companies without degrading the functionality of the sites that you visit. You can easily unblock a third party that you trust by clicking TheGoodData icon and then clicking on the name of the third party you want to allow, under the “Evil Data” area or simply allowing all tracking of a particular website if you feel that the extension is affecting your experience.</p>
                  <p>Besides blocking browsing threats, TheGoodData captures your search queries and, if you allow it, sells anonymized data after discarding queries that may contain sensitive terms (political, sexual, religious or health related). This data is sold to search retargeting players enabling them to display ads related to your searches. Thanks to TheGoodData these players can only do it with your permission and by paying a fee to TheGoodData in exchange. 100% of the money earned  thanks to your collaboration is then reinvested in Social Good projects and in improving TheGoodData service.</p>
                </li>
                <li>
                  <em>What kind of projects does TheGoodData fund with my data?</em>
                  <p>50% of the money collected is reinvested in microloan credits to alleviate poverty in developing countries. This investment is done via Zidisha.</p>
                  <p>The reason for choosing Zidisha is threefold:</p>
                  <ul class="clearfix">
                    <li><p>we believe that our data can be Good not only for our users and Members, but also for humanity</p> </li>
                    <li><p>we support the same principles of collaboration, transparency and Social Good that Zidisha does</p> </li>
                    <li><p>these microloans help to create opportunities where there are so few and does not erode our Members assets, since most of these loans are usually paid back by lenders.</p></li>
                  </ul>
                </li>
                <li>
                  <em>Why are some icons red, green and orange?</em>
                  <p>Red = blocked. Green = allowed. Orange = traded with your permission.</p>
                </li>
                <li>
                  <em>Why are the Content threats in green by default?</em>
                  <p>By default, we do not block third parties that are critical to the delivery of content to a web page. However if you would like to block this third partie content on the site you’re visiting, simply click these threats and they will change to red, indicating that they are being blocked.</p>
                </li>
                <li>
                  <em>What are the “Whitelist this site” and “Allow social networks” extension features?</em>
                  <p>These features provides you with the ability to unblock some or all third parties on the site you are visiting with a single click. This can be especially useful if you ever notice that certain elements of a site are not functioning the way they normally do.</p>
                </li>
                <li>
                  <em>How are the different user levels calculated?</em>
                  <p>User levels are based on your degree of collaboration with TheGoodData during the last 30 days. The more data you let us trade for a good cause and the more you are involved in TheGoodData company, the higher level you will achieve:</p>
                  <ul class="clearfix">
                    <li>
                      <p>Apprentice: if the user is among the 5% of people that that have contributed with the least amount of data items</p>
                    </li>
                    <li>
                      <p>Journeyman: If the user has contributed with more data items than Apprentice users but has not yet become a Member of TheGoodData</p>
                    </li>
                    <li>
                      <p>Owner: If the user has become a Member of TheGoodData </p>
                    </li>
                    <li>
                      <p>Expert: If the Member is among the top 20% of data contributors</p>
                    </li>
                    <li>
                      <p>Collaborator: If the Member has participated in the online collaboration platform during the last month </p>
                    </li>
                  </ul>
                </li>
                <li>
                  <em>What are the “Store” and “Share” extension features?</em>
                  <p>In case you don’t want to store your browsing history and your non-sensitive queries in our servers you can change this setting in the extension at any time. You can also decide not to sell any of your search data. No matter what you decide concerning these two settings, you will always enjoy TheGoodData threat detection service.</p>
                </li>
                <li id="search_query_trade">
                  <em>Why is the extension not trading my the search queries?</em>
                  <p>TheGoodData extension only trade queries if the following criteria are met: </p>
                  <ul class="clearfix">
                    <li>
                      <p>You have performed the query in the Chrome browser, with the extension enabled, and using either Google, Bing or Yahoo search engines.</p>
                    </li>
                    <li>
                      <p>The query does not contain any sensitive terms. To the sake of caution we may discard queries that pose a minor risk of containing sensitive terms.</p>
                    </li>
                    <li>
                      <p>The query is written in English. At this early stage we are guessing the query language based on browser default language. It might well be that you have written your query in English but we have discarded it because your browser language is a different one. We will improve this feature in the future.</p>
                    </li>
                  </ul>
                </li>
                <li>
                  <em>Why do you store information on TheGoodData servers?</em>
                  <p>TheGoodData aims to harvest, process and trade on your behalf as much data as you allow us to. We are currently trading search data, but we expect to trade data based on browsing history soon. This information is anonymized and stored on our servers following demanding security standards. You can at all times change this permission, access or delete any information stored about you.</p>
                </li>
                <li>
                  <em>Will TheGoodData work if I have multiple blocking extensions installed in my browser?</em>
                  <p>In order for TheGoodData to work in Chrome, it must be the most recent blocking extension installed.</p>
                </li>
                <li>
                  <em>How do I disable or uninstall TheGoodData?</em>
                  <p>First off, we are sad to see you go. If you have a minute after following the instructions below, please tell us your reason for unsuscribing at info@thegooddata.org as it will help us to improve our service</p>
                  <p>In Chrome, please open the Window menu and then choose the Extensions item. Uncheck the Enabled button to disable or click the trash icon to uninstall.</p>
                </li>
              </ul>
            </div>
            <div class="tab-pane" id="membership">
              <ul class="clearfix">
                <li>
                  <em>What does becoming a Member of TheGoodData mean?</em>
                  <p>Members of the company have similar rights as owners have in any other company, including access to company information, attending and voting in General Meetings, and electing or being elected as company Directors among other rights. The rights and duties of Members are explained in the company's Primary and Secondary Rules.</p>
                </li>
                <li>
                  <em>How can I become a Member?</em>
                  <p>To become a Member you must have used the service in the past 3 months and be at least 16 years old. If you fulfill these criteria you can apply for Membership via the website under the “collaborate” button at the top of the homepage. You will be asked to accept the Primary Rules and Company Principles and, if your application is approved, you will have to buy one company share.</p>
                </li>
                <li>
                  <em>Do I need to pay for a share to become a Member?</em>
                  <p>The short answer is no. As TheGoodData is registered as an Industrial and Provident Society, we are forced by law to ask our Members to own a fully paid share. In order to facilitate the process we have reduced the share price to the minimum possible (1 pence) and created a 0-interest loan agreement so you can buy that share without making any payment. If you ever terminate your Membership, this loan is cancelled against the transfer of the share ownership to TheGoodData. No payment is required for this either.</p>
                  <p>However, you are welcome to buy the 1p share paying with bitcoins or even supporting us with a donation from which we will deduct the 1p to give you your share.</p>
                </li>
                <li>
                  <em>Are there any Membership rules?</em>
                  <p>Main corporate rules are included in the Primary Rules which are agreed when becoming a member. Day-to-day governance rules are included in the Secondary Rules. We encourage you to read both documents to find answers to company related topics not covered by these FAQs. In the case of any unintended discrepancies, the Primary and Secondary Rules will prevail over the FAQs or any other company material.</p>
                </li>
                <li>
                  <em>How can Membership be cancelled?</em>
                  <p>A Member can decide to terminate their Membership at anytime, by communicating their wish to do so to <a href="mailto:members@thegooddata.org">members@thegooddata.org</a>. Membership will also be cancelled due to a lack of use of the service during 3 consecutive months or due to the failure to hold one Membership share. The Membership Committee can also decide to expel a Member if they haves acted against company interests or principles, if they have repeatedly misbehaved in company meetings or forums or if they have provided false information to the company. Membership Committee will be formed by company Members designated individuals. </p>
                  <p>If Membership comes to an end for any of these reasons, the Member must sell back their share to the company at its nominal value.</p>
                </li>
              </ul>
            </div>
            <div class="tab-pane" id="collaborators">
              <ul class="clearfix">
                <li>
                  <em>How can I collaborate with TheGoodData?</em>
                  <p>The easiest and most effective way to collaborate with TheGoodData is by using the service and asking others to do so.</p>
                  <p>Besides that, you can support us as much as you want. TheGoodData is a collaborative company and is open to everyone. We have built a platform at <a href="https://collaborate.thegooddata.org/">https://collaborate.thegooddata.org/</a> that will facilitate your access to any relevant information about the company, and aso provides you with an opportunity to comment on or lead a discussion about existing or new lines of business. We would love to see your participation there.</p>
                </li>
                <li>
                  <em>Can I contact company Directors directly?</em>
                  <p>Transparency also means direct communication. If you have any ideas for improvement or expertise that can be useful to us, you can email or make a hangout call to our company Director Marcos Menendez at <a href="mailto:marcos@thegooddata.org">marcos@thegooddata.org</a></p>
                </li>
                <li>
                  <em>Are coders rewarded?</em>
                  <p>In case you want to build any kind of new service functionality by leveraging on our assets, you are welcome to join our Coder’s Program. One sixth of company's revenues will be reserved for all coders during the six years that follow their contributions.</p>
                  <p>Please contact any of our company Directors or write to <a href="mailto:coders@thegooddata.org">coders@thegooddata.org</a> describing your idea, the expected level of effort needed and a CV outline to receive a strategic priority evaluation. </p>
                </li>
                <li id="rewards_calculation">
                  <em>How are rewards calculated?</em>
                  <p>In a given year, code released during the previous six years will be rewarded with one sixth of company revenues. They will all be rewarded proportionally considering:</p>
                  <ul class="clearfix">
                    <li>
                      <p>Their strategic importance: value provided by TheGoodData prior to starting developments</p>
                    </li>
                    <li>
                      <p>The level of effort: preferably measured preferably by lines of code or alternatively the estimated number of hours dedicated.</p>
                    </li>
                    <li>
                      <p>The output quality evaluated by other coders participating in the program</p>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="last_edit">
        <p>
          Last edit – May 2014.</br>
          If you have another question that has not been answered above, please <a href="mailto:info@thegooddata.org?subject=Question reported from TheGoodData webpage">email us</a>
        </p>
      </div>

    </div>
  </section>
</div>

<script>
  
$(document).ready(function(){

  $('.faq .tab-pane>ul>li p').hide();
  $('.faq .tab-pane>ul>li ul').hide();

  $('.faq .tab-pane>ul>li').click(function(){
    $(this).find('p').slideToggle(300);
    $(this).find('ul').slideToggle(300);
    $(this).toggleClass('active');
  });

  $('.faq .tab-pane>ul>li p, .faq .tab-pane>ul>li ul').click(function(event){
    event.stopPropagation();
  }); 
});

</script>



  <!-- END main content -->